from pickle import load
with open('clean_data.pkl', 'rb') as f:
    user_search_list = load(f)
    final_recipes_data = load(f)
    cuisine_region_list = load(f)
    dessert_list = load(f)
    maindish_list = load(f)
    sidedish_list = load(f)
    drink_list = load(f)
    appetizer_snack_list = load(f)
    european_list = load(f)
    latin_list = load(f)
    asian_list = load(f)
    african_list = load(f)
    brands_list = load(f)
    middle_eastern_list = load(f)
